reflectme/models.py
import json

from sqlalchemy.types import TypeDecorator, TEXT

from .database import db


class JSONEncodedDict(TypeDecorator):
    impl = TEXT

    def process_bind_param(self, value, dialect):
        if value is not None:
            value = json.dumps(value)

        return value

    def process_result_value(self, value, dialect):
        if value is not None:
            value = json.loads(value)
        return value


class Path(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    location = db.Column(db.String(255), index=True)
    status = db.Column(db.Integer)
    headers = db.Column(db.Text)
    response = db.Column(db.Text)
    records = db.relationship('Record', backref='path', lazy='joined', order_by="desc(Record.visited)")


class Record(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    path_id = db.Column(db.Integer, db.ForeignKey('path.id'))

    visited = db.Column(db.DateTime)
    request_ip = db.Column(db.String(255))
    request_content = db.Column(db.Text)

reflectme/forms.py
from flask_wtf import Form
from wtforms import TextField, TextAreaField
from wtforms.validators import DataRequired, Optional, ValidationError
from sqlalchemy.orm.exc import MultipleResultsFound, NoResultFound

from .utils import parse_headers
from .models import Path

class PathForm(Form):
    location = TextField('location')
    status = TextField('status', default="200")
    headers = TextAreaField('headers')
    response = TextAreaField('response')

    def validate_headers(form, field):
        if field.data:
            try:
                parse_headers(field.data)
            except:
                raise ValidationError('Headers must be one per-line, with a colon between name and value.')

    def validate_location(form, field):
        if not field.data:
            raise ValidationError('Location is required')

        path = Path.query.filter(Path.location == field.data).first()
        if path:
            raise ValidationError('A Path with that URL already exists')

reflectme/app.py
from flask import Flask

from .database import db
from .models import *
from .views import reflectme

class WSGICopyBody(object):
    def __init__(self, application):
        self.application = application

    def __call__(self, environ, start_response):

        from cStringIO import StringIO
        length = environ.get('CONTENT_LENGTH', '0')
        length = 0 if length == '' else int(length)

        body = environ['wsgi.input'].read(length)
        environ['body_copy'] = body
        environ['wsgi.input'] = StringIO(body)

        # Call the wrapped application
        app_iter = self.application(environ,
                                    self._sr_callback(start_response))

        # Return modified response
        return app_iter

    def _sr_callback(self, start_response):
        def callback(status, headers, exc_info=None):

            # Call upstream start_response
            start_response(status, headers, exc_info)
        return callback

def create_app(database='database.db', testing=False):
    """Application factory"""

    app = Flask(__name__, instance_relative_config=True)
    app.testing = testing

    app.config.from_object('reflectme.settings')
    app.config.from_pyfile('settings.py', silent=True)

    database_uri = 'sqlite:///{0}'.format(database)
    app.config['SQLALCHEMY_DATABASE_URI'] = database_uri
    db.init_app(app)

    if not testing:
        with app.app_context():
            db.create_all()

    app.register_blueprint(reflectme)

    app.wsgi_app = WSGICopyBody(app.wsgi_app)
    return app

reflectme/views.py
import datetime
import json

from flask import render_template, Blueprint, abort, request, \
        redirect, url_for, render_template
from sqlalchemy.orm.exc import NoResultFound
from pygments import highlight
from pygments.lexers import HttpLexer
from pygments.formatters import HtmlFormatter

from .database import db
from .models import Path, Record
from .forms import PathForm
from .utils import parse_headers

reflectme = Blueprint('reflectme', __name__)

def get_path_instance(location):
    try:
        path = Path.query.filter(Path.location == location).one()
    except NoResultFound:
        abort(404)
    return path

@reflectme.route('/<path:location>', methods=['GET', 'POST', 'DELETE', 'PUT'])
def view_path(location):
    path = get_path_instance(location)

    record = Record()
    record.visited = datetime.datetime.now()
    record.path = path
    record.request_ip = request.remote_addr

    http_request = render_template('http_request.txt', request=request)
    formatted_request = highlight(http_request, HttpLexer(), HtmlFormatter())
    record.request_content = formatted_request

    db.session.add(record)
    db.session.commit()

    headers = parse_headers(path.headers)
    return (path.response, 200, headers)

@reflectme.route('/inspect/<path:location>')
def inspect_path(location):
    path = get_path_instance(location)

    headers = parse_headers(path.headers)
    http_response = render_template('http_response.txt', path=path, headers=headers)
    formatted_response = highlight(http_response, HttpLexer(), HtmlFormatter())

    return render_template('inspect.html', path=path, formatted_response=formatted_response)

@reflectme.route('/', methods=['GET', 'POST'])
def index():
    current_paths = Path.query.all()

    form = PathForm()
    if form.validate_on_submit():
        path = Path()
        form.populate_obj(path)
        db.session.add(path)
        db.session.commit()
        return redirect(url_for('.inspect_path', location=path.location))
    return render_template('index.html', form=form, current_paths=current_paths)

reflectme/templates/index.html
{% extends "master.html" %}

{% macro input(field) -%}
  <div class="form-group row">
    <label class="control-label col-sm-2">{{field.name}}</label>
    <div class="col-sm-6">
        {{field(class_='form-control')}}
    </div>
  </div>
{%- endmacro %}

{% block content %}

<div class="row">
    <div class="col-sm-6">
        <h3>Paths</h3>
        <ul>
            {% for path in current_paths %}
            <li><a href="/inspect/{{path.location}}">/{{path.location}}</a></li>
            {% endfor %}
        </ul>
    </div>
</div>

<form method="POST" action="/" class="form-horizontal" role="form">
    <h3>New Path</h3>
    {{ form.csrf_token }}
    {% if form.errors %}
    <div class="alert alert-danger">
        <strong>Errors</strong>
    <ul class="errors">
        {% for field_name, field_errors in form.errors|dictsort if field_errors %}
            {% for error in field_errors %}
                <li>{{ form[field_name].label }}: {{ error }}</li>
            {% endfor %}
        {% endfor %}
    </ul>
    </div>
    {% endif %}

    {{ input(form.location) }}
    {{ input(form.headers) }}
    {{ input(form.response) }}

    <div class="form-group row">
        <label class="control-label col-sm-2"></label>
        <div class="col-sm-6">
            <input type="submit" value="Create" class="btn btn-primary">
        </div>
    </div>
</form>
{% endblock %}

reflectme/templates/inspect.html
{% extends "master.html" %}
{% block content %}
<h1>Inspecting <em>/{{path.location}}</em></h1>

<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Responding with...</h3>
            </div>
            <div class="panel-body">
                {{ formatted_response | safe }}
            </div>
        </div>
    </div>
</div>

<h3>Record Count: {{ path.records | count}}</h3>

<div class="panel-group" id="accordion">
    {% for record in path.records %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="#path_{{record.id}}">
                    Request from <strong>{{record.request_ip}}</strong> @ <em>{{record.visited}}</em>
                </a>
            </h4>
        </div>
        <div id="path_{{record.id}}" class="panel-collapse collapse {% if loop.first %}in{% endif %}">
            <div class="panel-body">
                {{ record.request_content | safe }}
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

reflectme/templates/master.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block title %}Reflect Me{% endblock %}</title>

        <link rel="stylesheet" href="{{url_for('static', filename='bootstrap.min.css') }}" type="text/css" media="screen" title="no title" charset="utf-8">  
        <link rel="stylesheet" href="{{url_for('static', filename='highlight.css') }}" type="text/css" media="screen" title="no title" charset="utf-8">  
        <style>
            .container {
                width: 970px;
                max-width: none !important;
            }
        </style>            
    </head>
    <body>
        <div class="navbar navbar-inverse" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="{{ url_for('reflectme.index') }}">Reflect Me</a>
                    <ul class="nav navbar-nav">
                        <li><a href="{{ url_for('reflectme.index') }}">Home</a></li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
        <script src="{{url_for('static', filename='jquery.min.js') }}" type="text/javascript" charset="utf-8"></script>
        <script src="{{url_for('static', filename='bootstrap.min.js') }}" type="text/javascript" charset="utf-8"></script>
    </body>
</html>